title: Cynthia Campos # your name (or website title) here
logo: "cynthia1.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi, my name is Cynthia. With 4+ years of professional experience working with data, I found myself enjoying solving the challenges that come with analyzing and communicating big data sets. Since I have always enjoyed solving puzzles, finding patterns and solutions that nobody else sees is the drive for me.
  <br><br>
  Extracting, cleaning, and visualizing data are skills that I will continue to master. If I could be of any value to you, please reach out to me. Thank you!
  <br><br>
  <a href="https://www.linkedin.com/in/cynthia-campos-b281a4192">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://public.tableau.com/app/profile/cynthia.campos">View My Tableau Profile</a> 
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
